
platform :ios, '8.0'
target 'BYBestThink' do
pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJExtension', '~> 3.0.11'
pod 'MJRefresh', '~> 3.1.10’
pod 'Masonry', '~> 1.0.1'
pod 'pop', '~> 1.0.9'
pod 'FMDB', '~> 2.6.2'
pod 'CocoaAsyncSocket', '~> 7.5.0'
pod 'DACircularProgress', '~> 2.3.1'
end
